In [1]:
%load_ext autoreload
%autoreload 2


import cadCAD
cadCAD.__file__

ModuleNotFoundError: No module named 'cadCAD'

In [1]:
from cadCAD.configuration.utils import config_sim
from cadCAD.configuration import Experiment
from cadCAD.engine import ExecutionMode, ExecutionContext
from cadCAD.engine import Executor

import pandas as pd

ModuleNotFoundError: No module named 'cadCAD'

In [3]:
system_params = {
    'add': [10]
}

initial_state = {
    'a': 0
}

In [4]:
from numpy import random

def update_a(params, substep, state_history, previous_state, policy_input, **kwargs):
    return 'a', previous_state['a'] + params['add'] * random.rand()

In [5]:
psubs = [
    {
        'policies': {},
        'variables': {
            'a': update_a
        }
    }
]

In [6]:
from cadCAD import configs
del configs[:] # Clear any prior configs

In [7]:
exp = Experiment()

sim_config = config_sim({
    "N": 3,
    "T": range(100),
    "M": system_params
})
# print(sim_config)

exp.append_configs(
    initial_state = initial_state,
    partial_state_update_blocks = psubs,
    sim_configs = sim_config
)
# print(sim_config)

[{'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 0}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 1}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 2}]

In [8]:
exec_mode = ExecutionMode()
local_mode_ctx = ExecutionContext(context=exec_mode.local_mode)

simulation = Executor(exec_context=local_mode_ctx, configs=configs)

raw_system_events, tensor_field, sessions = simulation.execute()

exec_mode.multi_proc

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

Execution Mode: local_proc
Configuration Count: 1
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (100, 1, 3, 1)
Execution Method: local_simulations
SimIDs   : [0, 0, 0]
SubsetIDs: [0, 0, 0]
Ns       : [0, 1, 2]
ExpIDs   : [0, 0, 0]
Execution Mode: parallelized
Total execution time: 0.03s

'multi_proc'

In [9]:
sessions

[{'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_0',
  'simulation_id': 0,
  'run_id': 0,
  'subset_id': 0,
  'subset_window': deque([0, 0])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_1',
  'simulation_id': 0,
  'run_id': 1,
  'subset_id': 0,
  'subset_window': deque([0, 0])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_2',
  'simulation_id': 0,
  'run_id': 2,
  'subset_id': 0,
  'subset_window': deque([0, 0])}]

In [10]:
simulation_result = pd.DataFrame(raw_system_events)
simulation_result

              a  simulation  subset  run  substep  timestep
0      0.000000           0       0    1        0         0
1      7.201762           0       0    1        1         1
2     12.985155           0       0    1        1         2
3     13.807088           0       0    1        1         3
4     19.579460           0       0    1        1         4
..          ...         ...     ...  ...      ...       ...
298  462.187262           0       0    3        1        96
299  464.684905           0       0    3        1        97
300  467.214356           0       0    3        1        98
301  473.321282           0       0    3        1        99
302  474.217380           0       0    3        1       100

[303 rows x 6 columns]

In [11]:
df = simulation_result.copy()

In [12]:
df[df['run'] == 1].head()

           a  simulation  subset  run  substep  timestep
0   0.000000           0       0    1        0         0
1   7.201762           0       0    1        1         1
2  12.985155           0       0    1        1         2
3  13.807088           0       0    1        1         3
4  19.579460           0       0    1        1         4

In [13]:
df[df['run'] == 2].head()

             a  simulation  subset  run  substep  timestep
101   0.000000           0       0    2        0         0
102   1.139284           0       0    2        1         1
103   4.291707           0       0    2        1         2
104   5.452919           0       0    2        1         3
105  11.419502           0       0    2        1         4

In [14]:
df[df['run'] == 3].head()

             a  simulation  subset  run  substep  timestep
202   0.000000           0       0    3        0         0
203   6.796407           0       0    3        1         1
204  12.630302           0       0    3        1         2
205  13.932469           0       0    3        1         3
206  20.626006           0       0    3        1         4

---

In [15]:
system_params = {
    'add': [10,10,10]
}

initial_state = {
    'a': 0
}

In [16]:
from numpy import random

def update_a(params, substep, state_history, previous_state, policy_input, **kwargs):
    return 'a', previous_state['a'] + params['add'] * random.rand()

In [17]:
psubs = [
    {
        'policies': {},
        'variables': {
            'a': update_a
        }
    }
]

In [18]:
from cadCAD import configs
del configs[:] # Clear any prior configs

In [19]:
exp = Experiment()

sim_config = config_sim({
    "N": 3,
    "T": range(100),
    "M": system_params
})

exp.append_configs(
    initial_state = initial_state,
    partial_state_update_blocks = psubs,
    sim_configs = sim_config
)

[{'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 0}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 1}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 0, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 0, 'run_id': 2}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 1, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 1, 'run_id': 0}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 1, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 1, 'run_id': 1}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 1, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 1, 'run_id': 2}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 2, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 2, 'run_id': 0}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 2, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 2, 'run_id': 1}, {'N': 1, 'T': range(0, 100), 'M': {'add': 10}, 'subset_id': 2, 'subset_window': deque([0, None], maxlen=2), 'simulation_id': 2, 'run_id': 2}]

In [20]:
exec_mode = ExecutionMode()
local_mode_ctx = ExecutionContext(context=exec_mode.local_mode)

simulation = Executor(exec_context=local_mode_ctx, configs=configs)

raw_system_events, tensor_field, sessions = simulation.execute()

                  ___________    ____
  ________ __ ___/ / ____/   |  / __ \
 / ___/ __` / __  / /   / /| | / / / /
/ /__/ /_/ / /_/ / /___/ ___ |/ /_/ /
\___/\__,_/\__,_/\____/_/  |_/_____/
by cadCAD

Execution Mode: local_proc
Configuration Count: 3
Dimensions of the first simulation: (Timesteps, Params, Runs, Vars) = (100, 1, 3, 1)
Execution Method: local_simulations
SimIDs   : [0, 0, 0, 1, 1, 1, 2, 2, 2]
SubsetIDs: [0, 0, 0, 1, 1, 1, 2, 2, 2]
Ns       : [0, 1, 2, 0, 1, 2, 0, 1, 2]
ExpIDs   : [0, 0, 0, 0, 0, 0, 0, 0, 0]
Execution Mode: parallelized
Total execution time: 0.06s

In [21]:
sessions

[{'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_0',
  'simulation_id': 0,
  'run_id': 0,
  'subset_id': 0,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_1',
  'simulation_id': 0,
  'run_id': 1,
  'subset_id': 0,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=0_2',
  'simulation_id': 0,
  'run_id': 2,
  'subset_id': 0,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=1_0',
  'simulation_id': 1,
  'run_id': 0,
  'subset_id': 1,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=1_1',
  'simulation_id': 1,
  'run_id': 1,
  'subset_id': 1,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=1_2',
  'simulation_id': 1,
  'run_id': 2,
  'subset_id': 1,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=2_0',
  'simulation_id': 2,
  'run_id': 0,
  'subset_id': 2,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=2_1',
  'simulation_id': 2,
  'run_id': 1,
  'subset_id': 2,
  'subset_window': deque([2, 2])},
 {'user_id': 'cadCAD_user',
  'experiment_id': 0,
  'session_id': 'cadCAD_user=2_2',
  'simulation_id': 2,
  'run_id': 2,
  'subset_id': 2,
  'subset_window': deque([2, 2])}]

In [22]:
simulation_result = pd.DataFrame(raw_system_events)
simulation_result

              a  simulation  subset  run  substep  timestep
0      0.000000           0       0    1        0         0
1      3.584995           0       0    1        1         1
2      8.837808           0       0    1        1         2
3     11.780959           0       0    1        1         3
4     21.201066           0       0    1        1         4
..          ...         ...     ...  ...      ...       ...
904  484.280146           2       2    3        1        96
905  491.913474           2       2    3        1        97
906  497.662872           2       2    3        1        98
907  502.692637           2       2    3        1        99
908  512.387846           2       2    3        1       100

[909 rows x 6 columns]

In [23]:
df = simulation_result.copy()

In [24]:
df[df['run'] == 1].head()

           a  simulation  subset  run  substep  timestep
0   0.000000           0       0    1        0         0
1   3.584995           0       0    1        1         1
2   8.837808           0       0    1        1         2
3  11.780959           0       0    1        1         3
4  21.201066           0       0    1        1         4

In [25]:
df[df['run'] == 2].head()

             a  simulation  subset  run  substep  timestep
101   0.000000           0       0    2        0         0
102   6.824417           0       0    2        1         1
103  10.798997           0       0    2        1         2
104  14.146451           0       0    2        1         3
105  17.351503           0       0    2        1         4

In [26]:
df[df['run'] == 3].head()

             a  simulation  subset  run  substep  timestep
202   0.000000           0       0    3        0         0
203   8.853333           0       0    3        1         1
204  10.047368           0       0    3        1         2
205  13.588649           0       0    3        1         3
206  16.557077           0       0    3        1         4